//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOAN_QUANCAFE
{
    using System;
    using System.Collections.Generic;
    
    public partial class LienHe
    {
        public int Id { get; set; }
        public string HoTen { get; set; }
        public string EmailOrPhone { get; set; }
        public string NoiDung { get; set; }
        public System.DateTime NgayGui { get; set; }
    }
}
