//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOAN_QUANCAFE
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QL_QuanCafeEntities : DbContext
    {
        public QL_QuanCafeEntities()
            : base("name=QL_QuanCafeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BinhLuan> BinhLuans { get; set; }
        public DbSet<tblChiTietHoaDon> tblChiTietHoaDons { get; set; }
        public DbSet<tblHinhAnh> tblHinhAnhs { get; set; }
        public DbSet<tblHoaDon> tblHoaDons { get; set; }
        public DbSet<tblKhachHang> tblKhachHangs { get; set; }
        public DbSet<tblLoaiSanPham> tblLoaiSanPhams { get; set; }
        public DbSet<tblNhaCungCap> tblNhaCungCaps { get; set; }
        public DbSet<tblNhanVien> tblNhanViens { get; set; }
        public DbSet<tblSanPham> tblSanPhams { get; set; }
        public DbSet<tblTinhTrang> tblTinhTrangs { get; set; }
        public DbSet<tblVaiTro> tblVaiTroes { get; set; }
        public DbSet<LienHe> LienHes { get; set; }
    }
}
