//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOAN_QUANCAFE
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLoaiSanPham
    {
        public tblLoaiSanPham()
        {
            this.tblSanPhams = new HashSet<tblSanPham>();
        }
    
        public int MaLoai { get; set; }
        public string TenLoai { get; set; }
        public string GhiChu { get; set; }
    
        public virtual ICollection<tblSanPham> tblSanPhams { get; set; }
    }
}
