//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOAN_QUANCAFE
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNhanVien
    {
        public tblNhanVien()
        {
            this.tblHoaDons = new HashSet<tblHoaDon>();
        }
    
        public int MaNV { get; set; }
        public string MatKhau { get; set; }
        public string TenNV { get; set; }
        public string GioiTinh { get; set; }
        public Nullable<int> NamSinh { get; set; }
        public Nullable<int> VaiTro { get; set; }
    
        public virtual ICollection<tblHoaDon> tblHoaDons { get; set; }
        public virtual tblVaiTro tblVaiTro { get; set; }
    }
}
