//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOAN_QUANCAFE
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSanPham
    {
        public tblSanPham()
        {
            this.BinhLuans = new HashSet<BinhLuan>();
            this.tblChiTietHoaDons = new HashSet<tblChiTietHoaDon>();
            this.tblHinhAnhs = new HashSet<tblHinhAnh>();
        }
    
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public string KichThuoc { get; set; }
        public Nullable<decimal> GiaBan { get; set; }
        public string MoTa { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<int> LoaiSP { get; set; }
        public Nullable<int> NhaCungCap { get; set; }
    
        public virtual ICollection<BinhLuan> BinhLuans { get; set; }
        public virtual ICollection<tblChiTietHoaDon> tblChiTietHoaDons { get; set; }
        public virtual ICollection<tblHinhAnh> tblHinhAnhs { get; set; }
        public virtual tblLoaiSanPham tblLoaiSanPham { get; set; }
        public virtual tblNhaCungCap tblNhaCungCap { get; set; }
    }
}
