//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOAN_QUANCAFE
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTinhTrang
    {
        public tblTinhTrang()
        {
            this.tblHoaDons = new HashSet<tblHoaDon>();
        }
    
        public int ID { get; set; }
        public string TinhTrangHoaDon { get; set; }
    
        public virtual ICollection<tblHoaDon> tblHoaDons { get; set; }
    }
}
